default_language_version:
  python: python3.8
default_stages: [commit, push]
repos:
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        args:
          - "--config"
          - "./pyproject.toml"

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args:
          - "--settings-file"
          - "./pyproject.toml"

  - repo: https://github.com/asottile/blacken-docs
    rev: v1.12.1
    hooks:
      - id: blacken-docs
        additional_dependencies: [black]

  # python linting
  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        exclude: (^tests/)|(notebooks/)
        args:
          # making isort line length compatible with black
          # https://flake8.pycqa.org/en/latest/user/error-codes.html
          - "--max-line-length=88"
          - "--max-complexity=18"
          - "--select=B,C,E,F,W,T4,B9"
          - "--ignore=E203,E266,E501,W503,F403,F401,E402,E741"
